/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/schema.json
export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  previousSlugs?: Array<string>;
  excerpt: string;
  featuredImage: ImageWithAlt;
  body: BlockContent;
  publishedAt: string;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  tags?: Array<string>;
  featured?: boolean;
  relatedPosts?: Array<
    {
      _key: string;
    } & PostReference
  >;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  keywords?: Array<string>;
  image?: ImageWithAlt;
  noIndex?: boolean;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        blank?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
  | ({
      _key: string;
    } & Callout)
  | ({
      _key: string;
    } & CodeBlock)
  | ({
      _key: string;
    } & Timeline)
>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  caption?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  pageTitle?: string;
  slug: Slug;
  previousSlugs?: Array<string>;
  summary: string;
  description: string;
  tags?: Array<string>;
  role?: string;
  year?: string;
  cardMedia: CaseStudyMedia;
  heroMedia?: CaseStudyMedia;
  links?: {
    figma?: string;
    behance?: string;
    live?: string;
  };
  overview?: Array<{
    label: string;
    value: string;
    _key: string;
  }>;
  challenge?: string;
  outcome?: string;
  personas?: Array<{
    label: string;
    title: string;
    description: string;
    _key: string;
  }>;
  process?: Array<{
    phase: "Discover" | "Define" | "Ideate" | "Design" | "Validate";
    title: string;
    body: Array<string>;
    media?: Array<
      {
        _key: string;
      } & CaseStudyMedia
    >;
    takeaways?: Array<string>;
    _key: string;
  }>;
  gallery?: Array<
    {
      _key: string;
    } & CaseStudyMedia
  >;
  reflection?: string;
  disclaimer?: string;
  seo?: Seo;
  order: number;
  hidden?: boolean;
};

export type CaseStudyMedia = {
  _type: "caseStudyMedia";
  kind: "image" | "embed";
  image?: ImageWithAlt;
  orientation?: "landscape" | "portrait";
  embedUrl?: string;
  embedTitle?: string;
  poster?: ImageWithAlt;
  aspect?: string;
  caption?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type MotionItem = {
  _id: string;
  _type: "motionItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  muxPlaybackId: string;
  poster?: ImageWithAlt;
  order: number;
  hidden?: boolean;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  role: string;
  company: string;
  companyUrl: string;
  dateLabel: string;
  logoLight: ImageWithAlt;
  logoDark: ImageWithAlt;
  responsibilities: Array<string>;
  skills: Array<string>;
  order: number;
};

export type ExternalProject = {
  _id: string;
  _type: "externalProject";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  url: string;
  image: ImageWithAlt;
  order: number;
  hidden?: boolean;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  greetingLatin: string;
  greetingSinhala: string;
  availabilityText?: string;
  workHeading: string;
  experienceHeading: string;
  blogHeading?: string;
  blogDescription?: string;
  motionHeading: string;
  motionDescription?: string;
  seo?: Seo;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName: string;
  brandLabel: string;
  canonicalUrl: string;
  author: {
    fullName: string;
    displayName: string;
    givenName: string;
    familyName: string;
    jobTitle: string;
    bio: string;
    profileImage?: ImageWithAlt;
    lanyardFront?: ImageWithAlt;
    lanyardBack?: ImageWithAlt;
  };
  email?: string;
  scheduleUrl?: string;
  resume?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    downloadName?: string;
    _type: "file";
  };
  socialLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  navigation: Array<
    {
      _key: string;
    } & Link
  >;
  footer?: {
    copyrightName?: string;
    sourceLabel?: string;
    sourceUrl?: string;
    inspirationLinks?: Array<
      {
        _key: string;
      } & Link
    >;
  };
  defaultSeo: Seo;
  twitterCreator?: string;
};

export type Timeline = {
  _type: "timeline";
  items: Array<{
    date: string;
    title?: string;
    body: string;
    _key: string;
  }>;
};

export type CodeBlock = {
  _type: "codeBlock";
  filename?: string;
  language?: string;
  code: string;
};

export type Callout = {
  _type: "callout";
  tone: "note" | "tip" | "warning";
  title?: string;
  body: string;
};

export type Link = {
  _type: "link";
  label: string;
  href: string;
  external?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | CategoryReference
  | PostReference
  | Post
  | Seo
  | BlockContent
  | SanityImageAssetReference
  | ImageWithAlt
  | Slug
  | CaseStudy
  | CaseStudyMedia
  | Category
  | MotionItem
  | Experience
  | ExternalProject
  | HomePage
  | SanityFileAssetReference
  | SiteSettings
  | Timeline
  | CodeBlock
  | Callout
  | Link
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[  _type == "siteSettings" && _id == "siteSettings"][0]{  ...,  author {    ...,    profileImage {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }},    lanyardFront {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }},    lanyardBack {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }}  },  resume {    ...,    asset->{url, originalFilename, mimeType}  },  defaultSeo {    ...,    image {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }}  }}
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: "siteSettings";
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName: string;
  brandLabel: string;
  canonicalUrl: string;
  author: {
    fullName: string;
    displayName: string;
    givenName: string;
    familyName: string;
    jobTitle: string;
    bio: string;
    profileImage: {
      alt: string;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
    } | null;
    lanyardFront: {
      alt: string;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
    } | null;
    lanyardBack: {
      alt: string;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
    } | null;
  };
  email?: string;
  scheduleUrl?: string;
  resume: {
    asset: {
      url: string;
      originalFilename: string | null;
      mimeType: string;
    } | null;
    media?: unknown;
    downloadName?: string;
    _type: "file";
  } | null;
  socialLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  navigation: Array<
    {
      _key: string;
    } & Link
  >;
  footer?: {
    copyrightName?: string;
    sourceLabel?: string;
    sourceUrl?: string;
    inspirationLinks?: Array<
      {
        _key: string;
      } & Link
    >;
  };
  defaultSeo: {
    _type: "seo";
    title?: string;
    description?: string;
    keywords?: Array<string>;
    image: {
      alt: string;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
    } | null;
    noIndex?: boolean;
  };
  twitterCreator?: string;
} | null;

// Source: sanity/lib/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[  _type == "homePage" && _id == "homePage"][0]{  ...,  seo {    ...,    image {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }}  }}
export type HOME_PAGE_QUERY_RESULT = {
  _id: "homePage";
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  greetingLatin: string;
  greetingSinhala: string;
  availabilityText?: string;
  workHeading: string;
  experienceHeading: string;
  blogHeading?: string;
  blogDescription?: string;
  motionHeading: string;
  motionDescription?: string;
  seo: {
    _type: "seo";
    title?: string;
    description?: string;
    keywords?: Array<string>;
    image: {
      alt: string;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
    } | null;
    noIndex?: boolean;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: RESUME_QUERY
// Query: *[  _type == "siteSettings" && _id == "siteSettings"][0]{  resume {    downloadName,    asset->{url, mimeType, originalFilename}  }}
export type RESUME_QUERY_RESULT = {
  resume: {
    downloadName: string | null;
    asset: {
      url: string;
      mimeType: string;
      originalFilename: string | null;
    } | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: CASE_STUDY_SLUGS_QUERY
// Query: *[  _type == "caseStudy" &&  hidden != true &&  defined(slug.current)] | order(order asc) {  "slug": slug.current}
export type CASE_STUDY_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: CASE_STUDIES_QUERY
// Query: *[  _type == "caseStudy" &&  hidden != true &&  defined(slug.current)] | order(order asc) {  _id,  title,  pageTitle,  "slug": slug.current,  previousSlugs,  summary,  description,  tags,  role,  year,  order,  cardMedia {  _key,  kind,  image {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }},  orientation,  embedUrl,  embedTitle,  poster {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }},  aspect,  caption}}
export type CASE_STUDIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  pageTitle: string | null;
  slug: string;
  previousSlugs: Array<string> | null;
  summary: string;
  description: string;
  tags: Array<string> | null;
  role: string | null;
  year: string | null;
  order: number;
  cardMedia: {
    _key: null;
    kind: "embed" | "image";
    image: {
      alt: string;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
    } | null;
    orientation: "landscape" | "portrait" | null;
    embedUrl: string | null;
    embedTitle: string | null;
    poster: {
      alt: string;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
    } | null;
    aspect: string | null;
    caption: string | null;
  };
}>;

// Source: sanity/lib/queries.ts
// Variable: CASE_STUDY_QUERY
// Query: *[  _type == "caseStudy" &&  hidden != true] | order(order asc) {  ...,  "slug": slug.current,  cardMedia {  _key,  kind,  image {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }},  orientation,  embedUrl,  embedTitle,  poster {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }},  aspect,  caption},  heroMedia {  _key,  kind,  image {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }},  orientation,  embedUrl,  embedTitle,  poster {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }},  aspect,  caption},  process[]{    ...,    media[] {  _key,  kind,  image {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }},  orientation,  embedUrl,  embedTitle,  poster {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }},  aspect,  caption}  },  gallery[] {  _key,  kind,  image {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }},  orientation,  embedUrl,  embedTitle,  poster {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }},  aspect,  caption},  seo {    ...,    image {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }}  }}
export type CASE_STUDY_QUERY_RESULT = Array<{
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  pageTitle?: string;
  slug: string;
  previousSlugs?: Array<string>;
  summary: string;
  description: string;
  tags?: Array<string>;
  role?: string;
  year?: string;
  cardMedia: {
    _key: null;
    kind: "embed" | "image";
    image: {
      alt: string;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
    } | null;
    orientation: "landscape" | "portrait" | null;
    embedUrl: string | null;
    embedTitle: string | null;
    poster: {
      alt: string;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
    } | null;
    aspect: string | null;
    caption: string | null;
  };
  heroMedia: {
    _key: null;
    kind: "embed" | "image";
    image: {
      alt: string;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
    } | null;
    orientation: "landscape" | "portrait" | null;
    embedUrl: string | null;
    embedTitle: string | null;
    poster: {
      alt: string;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
    } | null;
    aspect: string | null;
    caption: string | null;
  } | null;
  links?: {
    figma?: string;
    behance?: string;
    live?: string;
  };
  overview?: Array<{
    label: string;
    value: string;
    _key: string;
  }>;
  challenge?: string;
  outcome?: string;
  personas?: Array<{
    label: string;
    title: string;
    description: string;
    _key: string;
  }>;
  process: Array<{
    phase: "Define" | "Design" | "Discover" | "Ideate" | "Validate";
    title: string;
    body: Array<string>;
    media: Array<{
      _key: string;
      kind: "embed" | "image";
      image: {
        alt: string;
        caption: string | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
        asset: {
          _id: string;
          url: string;
          metadata: {
            dimensions: SanityImageDimensions | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
      orientation: "landscape" | "portrait" | null;
      embedUrl: string | null;
      embedTitle: string | null;
      poster: {
        alt: string;
        caption: string | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
        asset: {
          _id: string;
          url: string;
          metadata: {
            dimensions: SanityImageDimensions | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
      aspect: string | null;
      caption: string | null;
    }> | null;
    takeaways?: Array<string>;
    _key: string;
  }> | null;
  gallery: Array<{
    _key: string;
    kind: "embed" | "image";
    image: {
      alt: string;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
    } | null;
    orientation: "landscape" | "portrait" | null;
    embedUrl: string | null;
    embedTitle: string | null;
    poster: {
      alt: string;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
    } | null;
    aspect: string | null;
    caption: string | null;
  }> | null;
  reflection?: string;
  disclaimer?: string;
  seo: {
    _type: "seo";
    title?: string;
    description?: string;
    keywords?: Array<string>;
    image: {
      alt: string;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
    } | null;
    noIndex?: boolean;
  } | null;
  order: number;
  hidden?: boolean;
}>;

// Source: sanity/lib/queries.ts
// Variable: EXTERNAL_PROJECTS_QUERY
// Query: *[  _type == "externalProject" &&  hidden != true] | order(order asc) {  _id,  title,  description,  url,  order,  image {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }}}
export type EXTERNAL_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  description: string;
  url: string;
  order: number;
  image: {
    alt: string;
    caption: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
  };
}>;

// Source: sanity/lib/queries.ts
// Variable: EXPERIENCES_QUERY
// Query: *[  _type == "experience"] | order(order asc) {  _id,  role,  company,  companyUrl,  dateLabel,  responsibilities,  skills,  order,  logoLight {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }},  logoDark {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }}}
export type EXPERIENCES_QUERY_RESULT = Array<{
  _id: string;
  role: string;
  company: string;
  companyUrl: string;
  dateLabel: string;
  responsibilities: Array<string>;
  skills: Array<string>;
  order: number;
  logoLight: {
    alt: string;
    caption: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
  };
  logoDark: {
    alt: string;
    caption: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
  };
}>;

// Source: sanity/lib/queries.ts
// Variable: MOTION_ITEMS_QUERY
// Query: *[  _type == "motionItem" &&  hidden != true] | order(order asc) {  _id,  title,  muxPlaybackId,  order,  poster {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }}}
export type MOTION_ITEMS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  muxPlaybackId: string;
  order: number;
  poster: {
    alt: string;
    caption: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: BLOG_POST_SLUGS_QUERY
// Query: *[  _type == "post" &&  defined(slug.current) &&  publishedAt <= now()] | order(publishedAt desc) {  "slug": slug.current}
export type BLOG_POST_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: BLOG_POSTS_QUERY
// Query: *[  _type == "post" &&  defined(slug.current) &&  publishedAt <= now()] | order(publishedAt desc) {  _id,  _updatedAt,  title,  "slug": slug.current,  excerpt,  publishedAt,  featured,  tags,  featuredImage {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }},  categories[]->{_id, title, "slug": slug.current},  body[]{    _type,    children[]{text},    title,    body,    code,    items[]{date, title, body}  }}
export type BLOG_POSTS_QUERY_RESULT = Array<{
  _id: string;
  _updatedAt: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  featured: boolean | null;
  tags: Array<string> | null;
  featuredImage: {
    alt: string;
    caption: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
  };
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
  }> | null;
  body: Array<
    | {
        _type: "block";
        children: Array<{
          text: string | null;
        }> | null;
        title: null;
        body: null;
        code: null;
        items: null;
      }
    | {
        _type: "callout";
        children: null;
        title: string | null;
        body: string;
        code: null;
        items: null;
      }
    | {
        _type: "codeBlock";
        children: null;
        title: null;
        body: null;
        code: string;
        items: null;
      }
    | {
        _type: "imageWithAlt";
        children: null;
        title: null;
        body: null;
        code: null;
        items: null;
      }
    | {
        _type: "timeline";
        children: null;
        title: null;
        body: null;
        code: null;
        items: Array<{
          date: string;
          title: string | null;
          body: string;
        }>;
      }
  >;
}>;

// Source: sanity/lib/queries.ts
// Variable: BLOG_POST_QUERY
// Query: *[  _type == "post" &&  slug.current == $slug &&  publishedAt <= now()][0]{  ...,  "slug": slug.current,  body[]{    ...,    _type == "imageWithAlt" => {      ...,      asset->{        _id,        url,        metadata {          dimensions,          lqip        }      }    }  },  featuredImage {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }},  categories[]->{_id, title, "slug": slug.current},  relatedPosts[]->{    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    featuredImage {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }}  },  seo {    ...,    image {  alt,  caption,  crop,  hotspot,  asset->{    _id,    url,    metadata {      dimensions,      lqip    }  }}  }}
export type BLOG_POST_QUERY_RESULT = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: string;
  previousSlugs?: Array<string>;
  excerpt: string;
  featuredImage: {
    alt: string;
    caption: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
  };
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          blank?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "callout";
        tone: "note" | "tip" | "warning";
        title?: string;
        body: string;
      }
    | {
        _key: string;
        _type: "codeBlock";
        filename?: string;
        language?: string;
        code: string;
      }
    | {
        _key: string;
        _type: "imageWithAlt";
        asset: {
          _id: string;
          url: string;
          metadata: {
            dimensions: SanityImageDimensions | null;
            lqip: string | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
      }
    | {
        _key: string;
        _type: "timeline";
        items: Array<{
          date: string;
          title?: string;
          body: string;
          _key: string;
        }>;
      }
  >;
  publishedAt: string;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
  }> | null;
  tags?: Array<string>;
  featured?: boolean;
  relatedPosts: Array<{
    _id: string;
    title: string;
    slug: string;
    excerpt: string;
    publishedAt: string;
    featuredImage: {
      alt: string;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
    };
  }> | null;
  seo: {
    _type: "seo";
    title?: string;
    description?: string;
    keywords?: Array<string>;
    image: {
      alt: string;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
    } | null;
    noIndex?: boolean;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[\n  _type == "siteSettings" && _id == "siteSettings"\n][0]{\n  ...,\n  author {\n    ...,\n    profileImage {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n},\n    lanyardFront {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n},\n    lanyardBack {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n}\n  },\n  resume {\n    ...,\n    asset->{url, originalFilename, mimeType}\n  },\n  defaultSeo {\n    ...,\n    image {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n}\n  }\n}': SITE_SETTINGS_QUERY_RESULT;
    '*[\n  _type == "homePage" && _id == "homePage"\n][0]{\n  ...,\n  seo {\n    ...,\n    image {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n}\n  }\n}': HOME_PAGE_QUERY_RESULT;
    '*[\n  _type == "siteSettings" && _id == "siteSettings"\n][0]{\n  resume {\n    downloadName,\n    asset->{url, mimeType, originalFilename}\n  }\n}': RESUME_QUERY_RESULT;
    '*[\n  _type == "caseStudy" &&\n  hidden != true &&\n  defined(slug.current)\n] | order(order asc) {\n  "slug": slug.current\n}': CASE_STUDY_SLUGS_QUERY_RESULT;
    '*[\n  _type == "caseStudy" &&\n  hidden != true &&\n  defined(slug.current)\n] | order(order asc) {\n  _id,\n  title,\n  pageTitle,\n  "slug": slug.current,\n  previousSlugs,\n  summary,\n  description,\n  tags,\n  role,\n  year,\n  order,\n  cardMedia {\n  _key,\n  kind,\n  image {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n},\n  orientation,\n  embedUrl,\n  embedTitle,\n  poster {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n},\n  aspect,\n  caption\n}\n}': CASE_STUDIES_QUERY_RESULT;
    '*[\n  _type == "caseStudy" &&\n  hidden != true\n] | order(order asc) {\n  ...,\n  "slug": slug.current,\n  cardMedia {\n  _key,\n  kind,\n  image {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n},\n  orientation,\n  embedUrl,\n  embedTitle,\n  poster {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n},\n  aspect,\n  caption\n},\n  heroMedia {\n  _key,\n  kind,\n  image {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n},\n  orientation,\n  embedUrl,\n  embedTitle,\n  poster {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n},\n  aspect,\n  caption\n},\n  process[]{\n    ...,\n    media[] {\n  _key,\n  kind,\n  image {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n},\n  orientation,\n  embedUrl,\n  embedTitle,\n  poster {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n},\n  aspect,\n  caption\n}\n  },\n  gallery[] {\n  _key,\n  kind,\n  image {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n},\n  orientation,\n  embedUrl,\n  embedTitle,\n  poster {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n},\n  aspect,\n  caption\n},\n  seo {\n    ...,\n    image {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n}\n  }\n}': CASE_STUDY_QUERY_RESULT;
    '*[\n  _type == "externalProject" &&\n  hidden != true\n] | order(order asc) {\n  _id,\n  title,\n  description,\n  url,\n  order,\n  image {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n}\n}': EXTERNAL_PROJECTS_QUERY_RESULT;
    '*[\n  _type == "experience"\n] | order(order asc) {\n  _id,\n  role,\n  company,\n  companyUrl,\n  dateLabel,\n  responsibilities,\n  skills,\n  order,\n  logoLight {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n},\n  logoDark {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n}\n}': EXPERIENCES_QUERY_RESULT;
    '*[\n  _type == "motionItem" &&\n  hidden != true\n] | order(order asc) {\n  _id,\n  title,\n  muxPlaybackId,\n  order,\n  poster {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n}\n}': MOTION_ITEMS_QUERY_RESULT;
    '*[\n  _type == "post" &&\n  defined(slug.current) &&\n  publishedAt <= now()\n] | order(publishedAt desc) {\n  "slug": slug.current\n}': BLOG_POST_SLUGS_QUERY_RESULT;
    '*[\n  _type == "post" &&\n  defined(slug.current) &&\n  publishedAt <= now()\n] | order(publishedAt desc) {\n  _id,\n  _updatedAt,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  featured,\n  tags,\n  featuredImage {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n},\n  categories[]->{_id, title, "slug": slug.current},\n  body[]{\n    _type,\n    children[]{text},\n    title,\n    body,\n    code,\n    items[]{date, title, body}\n  }\n}': BLOG_POSTS_QUERY_RESULT;
    '*[\n  _type == "post" &&\n  slug.current == $slug &&\n  publishedAt <= now()\n][0]{\n  ...,\n  "slug": slug.current,\n  body[]{\n    ...,\n    _type == "imageWithAlt" => {\n      ...,\n      asset->{\n        _id,\n        url,\n        metadata {\n          dimensions,\n          lqip\n        }\n      }\n    }\n  },\n  featuredImage {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n},\n  categories[]->{_id, title, "slug": slug.current},\n  relatedPosts[]->{\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    publishedAt,\n    featuredImage {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n}\n  },\n  seo {\n    ...,\n    image {\n  alt,\n  caption,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {\n      dimensions,\n      lqip\n    }\n  }\n}\n  }\n}': BLOG_POST_QUERY_RESULT;
  }
}
